version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: timeadmin-mongodb-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: timeadministrator
    volumes:
      - mongodb_data:/data/db
    networks:
      - timeadmin-network

networks:
  timeadmin-network:
    driver: bridge

volumes:
  mongodb_data: